version: '3.2'

services:

  nginx:
    image: nginx:1.25.2
    restart: always
    container_name: nginx
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./settings/nginx/default.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  rabbitmq:
    image: rabbitmq:3.9.29-management
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - ./rabbitmq/state:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit ${RABBITMQ_MEMORY_LIMIT}
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7.2.3
    container_name: redis
    ports:
      - 6379:6379